In [1]:
import numpy as np

### np배열
- homogeneous type 모든 원소가 같은 자료형
- 원소의 갯수는 변경 불가능하다 => 차원은 변경가능하다
- 배열의 attribute 존재 ndim shape dtype
- vector operation가능

In [4]:
def arrayinfo(array):
    print('type :',type(array))
    print('shape :',array.shape)
    print('dimension :',array.ndim)
    print('dtype :',array.dtype)
    print(array)

In [5]:
array01 = np.array((1,2,3,4))
arrayinfo(array01)

type : <class 'numpy.ndarray'>
shape : (4,)
dimension : 1
dtype : int64
[1 2 3 4]


In [7]:
# 벡터 연산
list01 = [1,2,3,4,5]
print([e*2 for e in list01])

print(np.array((1,2,3,4,5))*2)

[2, 4, 6, 8, 10]
[ 2  4  6  8 10]


### 배열을 생성하는 방법
- np.array()

In [17]:
array01 = np.array([1,2,3,4])
arrayinfo(array01)

# resizing 크기는 변경 불가능하다
print(np.append(array01,5)) # 새로운 객체다
print(array01)

type : <class 'numpy.ndarray'>
shape : (4,)
dimension : 1
dtype : int64
[1 2 3 4]
[1 2 3 4 5]
[1 2 3 4]


- 요소의 타입을 변경 

In [36]:
array01 = np.array([1,2,3,4])
array01 = array01.astype(np.float)
arrayinfo(array01)

type : <class 'numpy.ndarray'>
shape : (4,)
dimension : 1
dtype : float64
[1. 2. 3. 4.]


In [163]:
# shape(4,)는 shpae(4,1)과 다르다
# demension도 다르고 shape도 다르다
array01 = np.array([1,2,3,4])   # 1차원 벡터 
arrayinfo(array01)

array01 = np.array([[1,2,3,4]]) # 2차원 행렬이다
arrayinfo(array01)

type : <class 'numpy.ndarray'>
shape : (4,)
dimension : 1
dtype : int64
[1 2 3 4]
type : <class 'numpy.ndarray'>
shape : (1, 4)
dimension : 2
dtype : int64
[[1 2 3 4]]


### 2차원 배열

In [10]:
array02 = np.array([[1,2,3,4],[1,2,3,4]],dtype=np.float)
arrayinfo(array02)

type : <class 'numpy.ndarray'>
shape : (2, 4)
dimension : 2
dtype : float64
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [19]:
## len()
array02 = np.array([[1,2,3,4],[1,2,3,4]],dtype=np.float)
print(array02)
print(len(array02))
print(len(array02[0])) # 행
print(len(array02[1])) # 열

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]]
2
4
4


### 3차원 배열

In [27]:
array03 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(array03)
print(array03.reshape(2,6))
print(array03.reshape(3,2,2))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [35]:
##len()
print(len(array03.reshape(3,2,2)))      # 3차원
print(len(array03.reshape(3,2,2)[0]))   # 2차원 (행)
print(len(array03.reshape(3,2,2)[0][0]))# 1차원 (열) 

3
2
2


### 배열의 인덱싱

In [42]:
# 1차원
array01 = np.array(10)
print(array01)

10


In [40]:
# 2차원 인덱싱도 가능하다
array02 = np.array([[1,2,3,4],[5,6,7,8]],dtype=np.float)
print(array02)

# 1행 1열
print(array02[0,0])

# 2행 3열
print(array02[1,2])

# 마지막 행의 마지막 열
print(array02[-1,-1])

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
1.0
7.0
8.0


### 배열의 인덱싱

In [46]:
array01 = np.arange(10)
print(array01)
print(array01[1:5])

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4]


In [50]:
array02 = np.array([[1,2,3,4],[5,6,7,8]],dtype=np.float)
print(array02)

# 첫번재행의 전체
print(array02[0,:])

# 두번째열의 전체
print(array02[:,1])

# 두번째 열이 두번째부터 끝까지
print(array02[1:,1])


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
[1. 2. 3. 4.]
[2. 6.]
[6.]


In [63]:
array01 = np.arange(15).reshape(3,5)
print(array01)
# 이 행렬에서 값 7 을 인덱싱한다.
array01[1,2]
# 이 행렬에서 값 14 을 인덱싱한다.
array01[-1,-1]
# 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
array01[1,1:3]
# 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
array01[1:3,2]
# 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
array01[0:2,3:5]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[3, 4],
       [8, 9]])

- ### fancy indexing  
    - integer list indexing (정수 배열 인덱싱)
- ### bool indexing
    - boolean mask indexing


In [73]:
# 짝수만
ary=np.arange(10)
print(ary%2==0)
ary[ary%2==0]

[ True False  True False  True False  True False  True False]


array([0, 2, 4, 6, 8])

In [72]:
ary = np.arange(4)
print(ary[[True,False,True,False]])
print(ary[np.array([True,False,True,False])])

[0 2]
[0 2]


In [76]:
# 홀수만
ary=np.arange(10)
print(ary[ary%2==1])
print(ary[[1,3,5,7,9]])

[1 3 5 7 9]
[1 3 5 7 9]


In [112]:
# 2차원에서도 fancy indexing 당연히 가능하다
array01=np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(3,4)
print(array01)
array01[[0,2],1]
array01[[0,2],1:2]


# [[1,3] [9,11]]로 꺼내보자 
array01[[0,2],[0,2]] # 얘는 이상하게 잘 안된다 브로드캐스팅 문제인거 같다

print(array01[[0,2],0:3:2])

print(array01[[0,2],:][:,[0,2]])

print(array01[[0,2]][:,[0,2]])



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  3]
 [ 9 11]]
[[ 1  3]
 [ 9 11]]
[[ 1  3]
 [ 9 11]]


In [211]:
a= np.arange(10).reshape(2,5)
print(a)
type(a[1,1])#=>ndarray도 아니고
a[1,1].ndim #=>0차원이다 

[[0 1 2 3 4]
 [5 6 7 8 9]]


0

In [87]:
## 인덱싱하면 차원의 허물어진다
# slicing하면 차원이 유지된다
# 재밌는 사실은 R에서는 1차원이나 0차원이나 사실은 동일하다
# 기본적으로 스칼라도 벡터 취급하기 때문
ndarray01 = np.arange(12).reshape(2,2,3)
print(ndarray01)
print("-"*20)
print(ndarray01[::,::,0]) # 마지막 컬럼 차원의 경계가 허물이고 차원이 2차원으로 줄었다
print(type(ndarray01[::,::,0]))
print(ndarray01[::,::,0].ndim) # 2차원


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
--------------------
[[0 3]
 [6 9]]
<class 'numpy.ndarray'>
2


### 넘파이 변수타입
- dtype: 'b'->boolean 'i'->integer 'f'->float 'U'->문자열...

In [118]:
print(np.array([1,2,3,4],dtype='U'))
print(np.array([1,2,3,4],dtype='i'))
print(np.array([1,2,3,4],dtype='f'))
print(np.array([1,2,3,4],dtype='b'))

['1' '2' '3' '4']
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


### inf & Not a Number

In [119]:
np.array([0,1,-1,0])/np.array([1,0,0,0])

<ipython-input-119-dc768ac6b521>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0])/np.array([1,0,0,0])
<ipython-input-119-dc768ac6b521>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,-1,0])/np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

### 배열 생성 함수
- np.array()
- np.arange()
- zeros() ones() empty() zeros_like() ones_like() linespace() logspace()

In [140]:
arrayinfo(np.arange(15))
arrayinfo(np.arange(1,15,2))
arrayinfo(np.arange(15).reshape(3,5))

type : <class 'numpy.ndarray'>
shape : (15,)
dimension : 1
dtype : int64
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
type : <class 'numpy.ndarray'>
shape : (7,)
dimension : 1
dtype : int64
[ 1  3  5  7  9 11 13]
type : <class 'numpy.ndarray'>
shape : (3, 5)
dimension : 2
dtype : int64
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [127]:
arrayinfo(np.zeros(10))
arrayinfo(np.zeros(10,dtype='U'))
arrayinfo(np.zeros(shape=(2,5)))

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : float64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : <U1
['' '' '' '' '' '' '' '' '' '']
type : <class 'numpy.ndarray'>
shape : (2, 5)
dimension : 2
dtype : float64
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [129]:
arrayinfo(np.ones(10))
arrayinfo(np.ones(shape=(2,5)))

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : float64
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
type : <class 'numpy.ndarray'>
shape : (2, 5)
dimension : 2
dtype : float64
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [133]:
# like 크기를 배낀다고 생각하자
arrayinfo(np.zeros_like(np.ones(10)))
arrayinfo(np.ones_like(np.arange(10).reshape(2,5)))

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : float64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
type : <class 'numpy.ndarray'>
shape : (2, 5)
dimension : 2
dtype : int64
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [135]:
arrayinfo(np.empty(shape=(4,3)))
arrayinfo(np.empty(shape=(4,3),dtype='U'))

type : <class 'numpy.ndarray'>
shape : (4, 3)
dimension : 2
dtype : float64
[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]
 [4.9e-323 5.4e-323 5.9e-323]]
type : <class 'numpy.ndarray'>
shape : (4, 3)
dimension : 2
dtype : <U1
[['' '' '']
 ['' '' '']
 ['' '' '']
 ['' '' '']]


In [143]:
arrayinfo(np.linspace(0,100,3))

type : <class 'numpy.ndarray'>
shape : (3,)
dimension : 1
dtype : float64
[  0.  50. 100.]


### 전치행렬
- T 
- np.transpose

In [146]:
np.arange(15).reshape(3,5).T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [148]:
np.transpose(np.arange(15).reshape(3,5))

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [161]:
# 1차원 배열에서는 의미가 없다

vec = np.arange(10)
print(vec.T)
print(vec.ndim)

np.arange(10).reshape(1,10).T
print(vec.reshape(1,10).T)
print(vec.reshape(1,10).ndim)

[0 1 2 3 4 5 6 7 8 9]
1
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
2


### 다차원을 1차원으로 만들어야 한다면?
- flatten
- ravel np.ravel

In [170]:
array01 = np.arange(10).reshape(2,5)
array01.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 배열 사용시 주의점
- 차원에대한 주의가 필요함

In [173]:
array01 = np.arange(10)
arrayinfo(array01)

array02 = np.arange(10).reshape(1,10)
arrayinfo(array02)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : int64
[0 1 2 3 4 5 6 7 8 9]
type : <class 'numpy.ndarray'>
shape : (1, 10)
dimension : 2
dtype : int64
[[0 1 2 3 4 5 6 7 8 9]]


- newaxis

In [180]:
array01 = np.arange(10)
print(array01[:,np.newaxis])
print(array01[np.newaxis])

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[0 1 2 3 4 5 6 7 8 9]]


### 모든 원소에대해 순차적으로 접근
- iternext(), finished

In [184]:
ary = np.arange(10)
for i in ary:
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 

In [191]:
# 이게 더 빠르다
ite = np.nditer(ary,flags=['c_index'])
while not ite.finished:
    idx = ite.index
    print(ary[idx],end=' ')
    ite.iternext()

0 1 2 3 4 5 6 7 8 9 

In [201]:
# 2차원은 어떻게 처리할까?
ary = np.arange(10).reshape(2,5)
for i in range(ary.shape[0]):
    for j in range(ary.shape[1]):
        print(ary[i][j],end=' ')

0 1 2 3 4 5 6 7 8 9 

In [200]:
ite = np.nditer(ary,flags=['multi_index'])
while not ite.finished:
    idx = ite.multi_index
    print(ary[idx],end=' ')
    ite.iternext()

0 1 2 3 4 5 6 7 8 9 