## Numpy03; reshape,flatten,ravel

In [4]:
import numpy as np

### reshape(), np.reshape()
- 제 1장에서 본적이있다. => 차원의 형태를 원하는 형식으로 지정해준다
- 단 배수가 맞지 않으면 에러난다
- R처럼 나머지 차원들은 알아서 유추 가능하다 => -1 을 인자로 넣어주자
- ndarray.shape 혹은 ndarray.dim 속성을 활용해 확인 가능하다

In [3]:
ndarray01 = np.arange(15)
print(ndarray01.reshape(3,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [21]:
ndarray01.reshape(3,5,order='F')
np.reshape(ndarray01,(3,5),order='F')

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
ndarray01 = np.arange(15).reshape(3,5)
print(ndarray01)
print('-'*20)
print(ndarray01.reshape(5,-1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
--------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


#### ⭐️어떤 순서로 reshape이 일어나는지 궁금하다
- 우선 1차원 데이터 형태로 자료들이 펼쳐진다
- option을 통해 우선순위 설정 가능
    1. order = 'C' (default) : row 우선 변경
    2. order = 'F' : column 우선 변경

In [33]:
ndarray01 = np.arange(15)
print(ndarray01.reshape(3,5))
ndarray01 = np.arange(15)
print(ndarray01.reshape(3,5,order='C'))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [34]:
ndarray01 = np.arange(15)
print(ndarray01.reshape(3,5,order='F'))

[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]


### newaxis
- 1D 의 ndarray를 row_vector col_vector로 사용하기 싶을때 자주 사용된다

- newaxis를 shape(,,,) 안에서 추가하고싶은 차원에 쓰자 => 그럼 차원이 추간된다

In [23]:
x = np.array([1,2,3])
# (,3) => (1,3)
print(x[np.newaxis,:])

# (,3) => (3,1)
print(x[:,np.newaxis])

[[1 2 3]]
[[1]
 [2]
 [3]]


In [24]:
x = np.array([[1,2,3],[4,5,6]])

# (2,3) => (1,2,3)
print(x[np.newaxis,:]) 

# (2,3) => (2,1,3)
print(x[:,np.newaxis])

# (2,3) => (2,3,1)
print(x[:,:,np.newaxis])

[[[1 2 3]
  [4 5 6]]]
[[[1 2 3]]

 [[4 5 6]]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


### ravel(), np.ravel()
- 다차원의 데이터를 1차원으로 변경
- order option 가능
    1. order = 'C' (default) : row 우선 변경
    2. order = 'F' : column 우선 변경

In [39]:
ndarray01 = np.arange(15).reshape(3,5)
print(ndarray01)
print()
print(ndarray01.ravel())  # default: order = 'C'

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [40]:
ndarray01 = np.arange(15).reshape(3,5)
print(ndarray01)
print()
print(ndarray01.ravel(order='F'))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[ 0  5 10  1  6 11  2  7 12  3  8 13  4  9 14]


### flatten()
- 다차원의 데이터를 1차원으로 변경
- order option 가능
    1. order = 'C' (default) : row 우선 변경
    2. order = 'F' : column 우선 변경

In [43]:
ndarray01 = np.arange(15).reshape(3,5)
print(ndarray01)
print()
print(ndarray01.flatten()) # defualt: order='C'


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [42]:
ndarray01 = np.arange(15).reshape(3,5)
print(ndarray01)
print()
print(ndarray01.flatten(order='F'))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[ 0  5 10  1  6 11  2  7 12  3  8 13  4  9 14]


### ⭐️ravel vs flatten
- ravel 은 view의 개념이다 => 원본 데이터 영향 o
- flatten 은 copy다 => 원본 데이터 영향 x

In [47]:
ndarray01 = np.arange(15).reshape(3,5)
temp = ndarray01.ravel()
temp[0]=1000
print(temp)
print(ndarray01)

[1000    1    2    3    4    5    6    7    8    9   10   11   12   13
   14]
[[1000    1    2    3    4]
 [   5    6    7    8    9]
 [  10   11   12   13   14]]


In [3]:
ndarray01 = np.arange(15).reshape(3,5)
temp = ndarray01.flatten()
temp[0]=1000
print(temp)
print(ndarray01)

[1000    1    2    3    4    5    6    7    8    9   10   11   12   13
   14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
