## Numpy04; concatenate, split, ufunc

In [2]:
import numpy as np

### concatenate
- concatenate([array,array,,,])
- axis option이 가능하다
    - 각 축이 0, 1, 2,,, 의 인덱스를 갖게 된다
- 동시에 3개 이상 결합도 가능하다

In [13]:
a = np.arange(10)
b = np.arange(10)
print(np.concatenate([a,b]))

[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]


In [14]:
a = np.arange(10).reshape(2,5)
b = np.arange(10).reshape(2,5)
print(np.concatenate([a,b]))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]


In [29]:
a = np.arange(10).reshape(2,5)
b = np.arange(10).reshape(2,5)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [19]:
a = np.arange(10).reshape(2,5)
b = np.arange(10).reshape(2,5)
print(np.concatenate([a,b],axis=0)) # 첫번째 축을 따라 결합한다

[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]


In [21]:
a = np.arange(10).reshape(2,5)
b = np.arange(10).reshape(2,5)
print(np.concatenate([a,b],axis=1))# 두번째 축을 따라 결합한다

[[0 1 2 3 4 0 1 2 3 4]
 [5 6 7 8 9 5 6 7 8 9]]


In [31]:
a = np.arange(12).reshape(2,2,3)
b = np.arange(12).reshape(2,2,3)
print(a)
print(b)
print(np.concatenate([a,b],axis=1))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]
  [ 6  7  8]
  [ 9 10 11]]]


#### np.vstack, np.hstack

In [22]:
a=np.array([1,2,3])
b=np.array([[4,5,6],
            [7,8,9]])

np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
a=np.array([[1],
           [5]])
b=np.array([[2,3,4],
            [6,7,8]])
np.hstack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])