## Numpy02; indexing, slicing, view, copy

In [3]:
import numpy as np

In [1]:
def arrayinfo(array):
    print('type :',type(array))
    print('shape :',array.shape)
    print('dimension :',array.ndim)
    print('dtype :',array.dtype)
    print(array)

### 배열 사용시 주의점
- 차원에대한 주의가 필요함
    - [1,2,3,4,5] : 1차원이다
    - [[1,2,3,4,5]] : 2차원이다
    - 비슷해보이지만 다르다 1차원의 shape은 (,5) 2차원의 shape은 (1,5)
    
- R과다르게 (axis1,aixs2,axis3,,) 순이다
    - 예를 들어 3차원 데이터라면 => (3차원,행,렬)

In [4]:
array01 = np.arange(10)
arrayinfo(array01)

array02 = np.arange(10).reshape(1,10)
arrayinfo(array02)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : int64
[0 1 2 3 4 5 6 7 8 9]
type : <class 'numpy.ndarray'>
shape : (1, 10)
dimension : 2
dtype : int64
[[0 1 2 3 4 5 6 7 8 9]]


### Indexing
- 파이썬 내장 배열과 달리 [axis1,axis2,,,]를 지원 => 여러차원에 대해 인덱싱 가능
- 순서에 유념
- indexing을 통한 값 update가능
- ndarray는 homogeneous 한 배열임을 유념

#### 1차원 벡터

In [18]:
ndarray01 = np.arange(12)
print(ndarray01[0])
print(ndarray01[-1])

0
11


#### 2차원 벡터

In [10]:
array02 = np.array([[1,2,3,4],[1,2,3,4]],dtype=np.float)
print(array02)
print(array02[0])      #행
print(array02[:,0])    #열

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]]
[1. 2. 3. 4.]
[1. 1.]
2
4
4


#### ⭐️ len함수
- 차원의 길이를 반환한다고 생각하자
- len(행) => 열의 갯수  (1차원 축의 길이)
- len(행렬) => 행의 갯수  (2차원 축의 길이)
- len(3차원) => 3차원 축의 길이

In [15]:
array02 = np.array([[1,2,3,4],[1,2,3,4]],dtype=np.float)
print(array02)
print(len(array02))    # 행의 갯수
print(len(array02[0])) # 열의 갯수
print(len(array02[1])) # 열의 갯수

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]]
2
4
4


#### 3차원 벡터

In [23]:
ndarray03 = np.arange(12).reshape(2,2,3)
print(ndarray03)
print(ndarray03[0])
print(ndarray03[0,0])
print(ndarray03[0,0,0])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[0 1 2]
 [3 4 5]]
[0 1 2]
0


In [28]:
array03 = np.arange(12).reshape(2,2,3)
print(array03)
print(len(array03))    # 3차원 축의 길이
print(len(array03[0])) # 행의 갯수(2차원 축)
print(len(array03[0,0])) # 열의 갯수(1차원 축)


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
2
2
3


#### indexing 통한 값을 update
- homogeneous type의 array이기 때문에 당연히 타입이 같거나 자동 형변환 가능해야한다
- 그렇지 않으면 에러발생한다

In [11]:
ndarray01 = np.arange(12).reshape(2,2,3)
print(ndarray01)
print('-'*15)
ndarray01[0,0,1]=10
print(ndarray01)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
---------------
[[[ 0 10  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [13]:
ndarray01 = np.arange(12).reshape(2,2,3)
print(ndarray01)
print(ndarray01.dtype) # int다
ndarray01[0,0,1]=10.1314341341341341341341341
print(ndarray01) # 자동적으로 형 변환한다

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
int64
[[[ 0 10  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [15]:
ndarray01 = np.arange(12).reshape(2,2,3)
print(ndarray01)
print(ndarray01.dtype) # int다
ndarray01[0,0,1]='hello python' # 당연히 type 에러난다

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
int64


ValueError: invalid literal for int() with base 10: 'hello python'

### Slicing
- i:j:k 기본 원리는 파이썬과 동일하다
- 각 차원별 슬라이싱이 가능하다 [i:j:k,i:j:k,,,,]
- 모든 차원을 명시해줄 필요 없다 => 2차원데이터도 [1] 이런식으로 하나의 차원으로 슬라이싱 가능
- 아무것도 값을 넣지 않고 [,,,,] 이건 에러난다 => ::라도 최소한으로 넣어주어야 한다

In [4]:
# 에러
ndarray01 = np.arange(12).reshape(2,2,3)
print(ndarray01[,1,])

SyntaxError: invalid syntax (<ipython-input-4-4a3e1bb7befa>, line 3)

#### 1차원


In [26]:
ndarray01 = np.arange(12)
# 파이썬 리스트처럼 원하는대로 가능하다
print(ndarray01[0:])
print(ndarray01[-4::-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[8 7 6 5 4 3 2 1 0]


#### 2차원

In [10]:
ndarray01 = np.arange(20).reshape(4,5)
print(ndarray01)
print('-'*20)
print(ndarray01[-2::-1])
print('-'*20)
print(ndarray01[-2::-1,::2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
--------------------
[[10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
--------------------
[[10 12 14]
 [ 5  7  9]
 [ 0  2  4]]


#### 3차원

In [23]:
ndarray01 = np.arange(12).reshape(2,2,3)
print(ndarray01)
print("-"*20)
print(ndarray01[::,::,0])
print("-"*20)
print(ndarray01[::,0,0:2])
print("-"*20)
print(ndarray01[::,::,0:2])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
--------------------
[[0 3]
 [6 9]]
--------------------
[[0 1]
 [6 7]]
--------------------
[[[ 0  1]
  [ 3  4]]

 [[ 6  7]
  [ 9 10]]]


#### ⭐️차원의 축소
- Ex) 1차원 데이터에서 인덱싱을 했을때는 => 차원이 0차원이된다 스칼라값이다
- Ex) 다차원 데이터에서 인덱싱이 된 차원의 경계는 허물어진다 => 차원의 축소
- Ex) slicing이 된 차원은 경계가 허물어지지 않는다

In [16]:
# 1차원
ndarray01 = np.arange(12)
print(type(ndarray01[0])) # 더이상 ndarray 객체가 아니다

<class 'numpy.int64'>


In [30]:
# 다차원
ndarray01 = np.arange(12).reshape(2,2,3)
print(ndarray01)
print("-"*20)
print(ndarray01[::,::,0])
# 마지막 컬럼 차원의 경계가 허물이지기 때문에 0과3이 같은 차원으로 들어가고 6과 9과 같은 차원
# 으로 들어갔다. 그렇지만 바깥쪽에 2개의 차원이 아직 경계가 허물어지지 않았다
# 따라서 [[0,3] [6,9]] 이런식의 결과가 출력될거다
print(type(ndarray01[::,::,0]))
print(ndarray01[::,::,0].ndim) # 2차원

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
--------------------
[[0 3]
 [6 9]]
<class 'numpy.ndarray'>
2


### slicing 은 view의 개념이다
- view라는 것은 즉 하위 배열을 수정하면 => 원래 배열이 변경된다
- 파이썬 내장 list는 slicing 하게 되면 객체의 주소가 다른 shallow copy => 원래 배열 변경되지 않는다

In [35]:
# built-in list
list01 = list(range(10))
list02 = list01[:]    # 새로운 주소에 shallow copy다
list02[0] = 1000
print(list01)         # 값이 바뀌지 않는다


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [38]:
# Numpy ndarray
ndarray01 = np.arange(12).reshape(2,2,3)

ndarray01[::,::,0] = np.arange(100,104).reshape(2,2) # 값이 바뀐다
print(ndarray01)


[[[100   1   2]
  [101   4   5]]

 [[102   7   8]
  [103  10  11]]]


In [36]:
# ndarray.copy는 deepcopy다
ndarray01 = np.arange(12).reshape(2,2,3)
ndarray02 = ndarray01.copy()
ndarray02[::,::,0] = np.arange(100,104).reshape(2,2) # 값이 바뀌지 않음

print(ndarray01)


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
