## Numpy04; concatenate, split, delete

In [2]:
import numpy as np

### concatenate
- 기본적으로 R에서 생각했던 c() rbind() cbind()의 개념은 버리자
- must have same dimension
- must have same shape except in the dimension given as axis
    - 주어진 axis를 제외한 나머지 차원의 형태가 같아야한다
    - Ex) axis = 0 으로 주어졌다면 => (2,3) (,3) 은 가능하다
    - Ex) axis = 1 으로 주어졌다면 => (2,3) (2,) 은 가능하다
 

#### 사용방법
- concatenate([array,array,,,],axis)
- axis option이 가능하다
    - 각 축이 0, 1, 2,,, 의 인덱스를 갖게 된다
- 동시에 3개 이상 결합도 가능하다

#### 다음의 상황은 에러가 발생한다
- 차원이 다를경우 => 분명히 차원이 같아야 된다고 했다 
- 차원이 다를경우에는 np.hstack np.vstack을  사용하자

In [11]:
a = np.arange(10).reshape(2,5)
b = np.arange(5)
np.concatenate([a,b])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [13]:
# 행결방법
a = np.arange(10).reshape(2,5)
b = np.arange(5).reshape(1,5) # 차원을 맞춰주면 가능하다 
np.concatenate([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

#### aixs의 개념
- 가장 중요한건 (면 행 열) 순이다
- 2차원에서 axis=0 은 행을 따라 axis=1은 열을 따라 진행한다
- 3차원에서 axis=0 은 면을 따라 axis=1 은 행을 따라 axis=2은 열을 따라 진행한다

In [3]:
# 1차원
# 애초에 차원이 하나밖에 없다 (,n)
# 그럼 axis=0밖에 없는거다
# axis=0의 방향으로 추가된다
a = np.arange(10)
b = np.arange(10)
print(np.concatenate([a,b]))

[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]


In [6]:
# 2차원 끼리
a = np.arange(10).reshape(2,5)
b = np.arange(10).reshape(2,5)

# axis = 0 은 행의 방향을따라 추가한다
print(np.concatenate([a,b],axis=0))

# axis =1 은 열의 방향을 따라 추가한다
print(np.concatenate([a,b],axis=1))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4 0 1 2 3 4]
 [5 6 7 8 9 5 6 7 8 9]]


In [7]:
# 아래 두개의 데이터은 둘다 3차원 데이터이다
a = np.arange(12).reshape(2,2,3)   # 면 행 열 순이다
b = np.arange(12).reshape(2,2,3)

# axis=2 열을 따라 추가한다
print(np.concatenate([a,b],axis=2))
print("-"*30)

# axis=1은 행을 따라 추가한다
print(np.concatenate([a,b],axis=1))
print("-"*30)

# axis=0은 면을 따라 추가한다
print(np.concatenate([a,b],axis=0))



[[[ 0  1  2  0  1  2]
  [ 3  4  5  3  4  5]]

 [[ 6  7  8  6  7  8]
  [ 9 10 11  9 10 11]]]
------------------------------
[[[ 0  1  2]
  [ 3  4  5]
  [ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]
  [ 6  7  8]
  [ 9 10 11]]]
------------------------------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


### np.vstack, np.hstack
- np.concatenate처럼 같은 차원일 필요는 없다
- 1차원일 경우
     - np.hstack의 경우는 그냥 하나의 축을따라 열이 추가된다
     - np.vstack의 경우 (1,N) 으로 reshape한 후 행이 추가된다
      
- 그 외의 경우
    - np.hstack의 경우는 열이 추가되기 때문에 행의 길이가 같아야한다
    - np.vstack의 경우는 행이 추가되기 때문에 열의 길이가 같아야한다

In [33]:
# hstack(1차원의 경우)
a = np.arange(5)
b = np.arange(5,10)
print(np.hstack([a,b]))


[0 1 2 3 4 5 6 7 8 9]


In [31]:
# hstack
# 행의 길이 같아야된다 => 잘생각해보면 행의 길이가 존재하려면 사실 무조건 2차원 이상이다
a=np.array([[1],
           [5]])
b=np.array([[2,3,4],
            [6,7,8]])
np.hstack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
# vsatck(1차원일경우)
a = np.arange(5)
b = np.arange(5,10)
print(np.vstack([a,b]))


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [16]:
# vstack
# 열의 길이가 같아야한다 => 열의 길이가 존재하기 때무네 단순 1차원 벡터도 추가가능한거다
a=np.array([1,2,3])    
b=np.array([[4,5,6],   
            [7,8,9]])

np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### r의 cbind와 rbind를 생각해보자

In [21]:
a = np.arange(5)
b = np.arange(5,10)

# rbind를 하고싶다
print(np.vstack([a,b]))

# cbind를 하고싶다
print(np.hstack([a.reshape(5,1),b.reshape(5,1)]))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [25]:
a = np.arange(5)
b = np.arange(25).reshape(5,5)

# rbind를 하고싶다
print(np.vstack([b,a]))

# cbind를 하고싶다
print(np.hstack([b,a.reshape(5,1)]))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [ 0  1  2  3  4]]
[[ 0  1  2  3  4  0]
 [ 5  6  7  8  9  1]
 [10 11 12 13 14  2]
 [15 16 17 18 19  3]
 [20 21 22 23 24  4]]


### stack
- 면을 추가한다고 생가각하자
- 행 열의 shpape이 같아야된다

In [38]:
ary01 = np.ones((3,4))
print(ary01)
ary02 = np.zeros((3,4))
print(ary02)
print('stack의 결과는 ')
print(np.stack([ary01,ary02]))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
stack의 결과는 
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### tile
- size를 지정해서 반복할수있다

In [39]:
print(np.tile(np.array([[1,2,3],[4,5,6]]),(3,2)))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [1 2 3 1 2 3]
 [4 5 6 4 5 6]]


### np.split
- np.split(array,[index,index,index,,,])
- [index,index,,,]에서 index는 포함되지 않고 쪼갠다 

In [48]:
x = np.arange(20)
print(np.split(x,[2,5,10]))

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]


### delete
- delete(array,대상,axis)
- axis를 따라 대상을 삭제한다
- axis를 지정하지 않으면 1차변환 후 삭제
- 원본 배열을 변경하지 않고 생로운 배열 return

In [43]:
array01 = np.random.randint(0,10,size=(3,4))
print(array01)

# 행을따라 두번째 행 삭제
print('행을따라 두번째 행 삭제')
print(np.delete(array01,1,0))

# 열을따라 두번째 열 삭제
print('행을따라 두번째 열 삭제')
print(np.delete(array01,1,1))

[[6 5 6 1]
 [9 4 7 8]
 [6 0 2 4]]
행을따라 두번째 행 삭제
[[6 5 6 1]
 [6 0 2 4]]
행을따라 두번째 열 삭제
[[6 6 1]
 [9 7 8]
 [6 2 4]]
