#### 머신러닝 개념(ML)

- 데이터를 기반으로 패턴을 학습하고 결과를 추론하는 알고리즘 기법
- 지도학습(Supervised Learning) 과 비지도학습(Un-Supervised Learning) , 강화학습(Reinforcement Learning)
- 지도학습   - 분류, 회귀
- 비지도학습 - 군집화(클러스터링) , 차원축소(PCA) 

#### 머신러닝 용어?
- 피처(feature) : 데이터의 일반 속성
- 레이블, 클래스, 타겟 값, 결정 값 : 정답데이터를 의미한다



In [107]:
import numpy  as np
import pandas as pd


import sklearn
from   sklearn.datasets import load_iris

from   sklearn.model_selection import train_test_split , KFold , StratifiedKFold , cross_val_score , cross_validate
from   sklearn.tree            import DecisionTreeClassifier
from   sklearn.metrics         import accuracy_score

sklearn.__version__

'0.24.1'

In [5]:
iris = load_iris()
print('type - ' , type(iris))
print('keys - ' , iris.keys())

type -  <class 'sklearn.utils.Bunch'>
keys -  dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [12]:
print('data - ' , iris.data , type(iris.data))
print()
print('target - ' , iris.target , type(iris.target))
print()
print('target_names - ' , iris.target_names)
print()
print('feature_names - ' , iris.feature_names)


data -  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.

In [17]:
print('feature , target를 이용해서 데이터 프레임을 만들어보자 - ')
print()
iris_label = iris.target
iris_data  = iris.data 

iris_frm = pd.DataFrame(data = iris_data , 
                        columns = iris.feature_names)
iris_frm['target'] = iris_label
iris_frm

feature , target를 이용해서 데이터 프레임을 만들어보자 - 



sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

#### Supervised Learning - classification
- step 01. 데이터세트 분리(학습 데이터, 테스트 데이터)
- step 02. 학습 데이터를 기반으로 ML 알고리즘을 적용해 학습 모델을 만든다 - fit()
- step 03. 분류예측을 수행(테스트 데이터) - predict()
- step 04. 평가

#### 분류(Classifier)
- DecisionTreeClassifier
- RandomForestClassifier
- GradientBoostingClassifier
- GaussianNB
- SVC

#### 회귀(Regressior)
- LinearRegression
- Ridge
- Lasso
- RandomForestRegression
- GradientBoostingRegression


In [25]:
print('학습데이터와 테스트데이터로 분리 - ')
print()
print()
X_train, X_test, y_train, y_test = train_test_split(iris_data  , 
                                                    iris_label ,
                                                    test_size = 0.2 , 
                                                    shuffle = False  ,
                                                    random_state = 200 ) 
print('train data  - ' , X_train)
print('train label - ' , y_train)
print()
print()
print('test data  - ' , X_test)
print('test label - ' , y_test)

학습데이터와 테스트데이터로 분리 - 


train data  -  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.

In [46]:
print('알고리즘이 적용된 모델을 선정해서 학습시켜보자 - model01 ')
print()
print()


dtc = DecisionTreeClassifier() 
dtc.fit(X_train , y_train)

알고리즘이 적용된 모델을 선정해서 학습시켜보자 - model01 




DecisionTreeClassifier()

In [47]:
print('새로운 데이터를(test) 이용해서 예측을 해 보자 - ')
print()
print()

y_predict = dtc.predict(X_test)
print('y_test    - ' , y_test)
print()
print('y_predict - ' , y_predict)

새로운 데이터를(test) 이용해서 예측을 해 보자 - 


y_test    -  [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]

y_predict -  [2 2 2 1 2 2 1 1 2 1 2 2 2 1 1 2 2 2 1 2 2 2 2 2 2 2 1 2 2 2]


In [48]:
print('예측 정확도 - ')
print()
print('예측 정확도 -  {0: .2f} '.format( accuracy_score(y_test , y_predict)))

예측 정확도 - 

예측 정확도 -   0.73 


In [63]:
print('데이터 프레임형식에서 학습데이터와 테스트데이터를 분리한다면 - ')
print()
print()
print('피처만 추출한다면 - ')
iris_feature_frm = iris_frm.iloc[ :  , : -1 ]

print('레이블만 추출한다면 - ')
iris_label_frm   = iris_frm.iloc[ :  , -1 ]

X_train, X_test, y_train, y_test = train_test_split(iris_feature_frm  , 
                                                    iris_label_frm ,
                                                    test_size = 0.2 , 
                                                    shuffle = True  ,
                                                    random_state = 200 ) 
print('train data  - ' , X_train)
print('train label - ' , y_train)
print()
print()
print('test data  - ' , X_test)
print('test label - ' , y_test)


데이터 프레임형식에서 학습데이터와 테스트데이터를 분리한다면 - 


피처만 추출한다면 - 
레이블만 추출한다면 - 
train data  -       sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
39                 5.1               3.4                1.5               0.2
99                 5.7               2.8                4.1               1.3
92                 5.8               2.6                4.0               1.2
4                  5.0               3.6                1.4               0.2
97                 6.2               2.9                4.3               1.3
..                 ...               ...                ...               ...
42                 4.4               3.2                1.3               0.2
68                 6.2               2.2                4.5               1.5
16                 5.4               3.9                1.3               0.4
105                7.6               3.0                6.6               2.1
26                 5.0               3.4                1.6   

In [64]:
print('알고리즘이 적용된 모델을 선정해서 학습시켜보자 - model02 ')
print()
print()


dtc02 = DecisionTreeClassifier() 
dtc02.fit(X_train , y_train)

알고리즘이 적용된 모델을 선정해서 학습시켜보자 - model02 




DecisionTreeClassifier()

In [65]:
print('새로운 데이터를(test) 이용해서 예측을 해 보자 - ')
print()
print()

y_predict = dtc02.predict(X_test)
print('y_test    - ' , y_test)
print()
print('y_predict - ' , y_predict)

새로운 데이터를(test) 이용해서 예측을 해 보자 - 


y_test    -  84     1
122    2
28     0
24     0
75     1
109    2
81     1
98     1
80     1
100    2
124    2
2      0
34     0
44     0
128    2
13     0
93     1
41     0
63     1
137    2
19     0
60     1
126    2
11     0
47     0
18     0
96     1
107    2
141    2
53     1
Name: target, dtype: int32

y_predict -  [1 2 0 0 1 2 1 1 1 2 2 0 0 0 2 0 1 0 1 2 0 1 2 0 0 0 1 2 2 1]


In [66]:
print('예측 정확도 - ')
print()
print('예측 정확도 -  {0: .2f} '.format( accuracy_score(y_test , y_predict)))

예측 정확도 - 

예측 정확도 -   1.00 


In [70]:
print('학습과 예측시 테스트데이터를 사용하지않고 학습데이터로만 학습과예측을 진행한다면? - ')
print()

print('피처만 추출한다면 - ')
iris_feature_frm = iris_frm.iloc[ :  , : -1 ]

print('레이블만 추출한다면 - ')
iris_label_frm   = iris_frm.iloc[ :  , -1 ]

X_train, X_test, y_train, y_test = train_test_split(iris_feature_frm  , 
                                                    iris_label_frm ,
                                                    test_size = 0.2 , 
                                                    shuffle = True  ,
                                                    random_state = 200 ) 

bad_dtc03 = DecisionTreeClassifier() 
bad_dtc03.fit(X_train , y_train)

y_predict = bad_dtc03.predict(X_train)


print()
print('예측 정확도 -  {0: .2f} '.format( accuracy_score(y_train , y_predict)))

학습과 예측시 테스트데이터를 사용하지않고 학습데이터로만 학습과예측을 진행한다면 - 

피처만 추출한다면 - 
레이블만 추출한다면 - 

예측 정확도 -   1.00 


#### 교차검증(Cross Validation)
- 과적합(overfitting)을 방지하기 위한 방법
- 데이터의 편중을 막기위해서

- KFold 방식

In [75]:
fold_iris = load_iris()

features = fold_iris.data
label    = fold_iris.target

fold_dt_clf = DecisionTreeClassifier()


In [77]:
print('5개의 폴더 세트를 분리하여 각 폴더 세트별 정확도를 담아보자 - ')
cv_accuracy = []
kfold = KFold(n_splits = 5 )  

5개의 폴더 세트를 분리하여 각 폴더 세트별 정확도를 담아보자 - 


In [83]:
n_iter = 0 

for train_idx , test_idx in kfold.split(features) :
#     print('train_idx - ' , train_idx )
#     print('test_idx  - ' , test_idx )
#     print()
    X_train , X_val = features[train_idx] , features[test_idx] 
    y_train , y_val = label[train_idx] , label[test_idx] 
    
    # 학습과 예측
    fold_dt_clf.fit(X_train , y_train)
    fold_pred = fold_dt_clf.predict(X_val)
    
    n_iter += 1
    
    # 학습데이터에 대한 검증 정확도 측정
    acc = accuracy_score(y_val , fold_pred)
    print('{} 교차검증 정확도 : {} , 학습 데이터 크기 : {} , 검증데이터 크기 : {}'.format(n_iter, acc, X_train.shape[0], X_val.shape[0]))
    print()
    cv_accuracy.append(acc)

print('교차검증 평균 정확도 : ' , np.mean(cv_accuracy) )     

1 교차검증 정확도 : 1.0 , 학습 데이터 크기 : 120 , 검증데이터 크기 : 30

2 교차검증 정확도 : 1.0 , 학습 데이터 크기 : 120 , 검증데이터 크기 : 30

3 교차검증 정확도 : 0.8333333333333334 , 학습 데이터 크기 : 120 , 검증데이터 크기 : 30

4 교차검증 정확도 : 0.9333333333333333 , 학습 데이터 크기 : 120 , 검증데이터 크기 : 30

5 교차검증 정확도 : 0.7666666666666667 , 학습 데이터 크기 : 120 , 검증데이터 크기 : 30

교차검증 평균 정확도 :  0.9066666666666667


- 불균형한 분포도를 가진 레이블 데이터 집합을 위한 KFold 방식 -> Stratifield KFold 
- 레이블의 분포를 먼저 고려한 뒤 이 분포와 동일하게 학습, 검증 데이터 세트로 분할

In [88]:
print('기존 KFold 방식의 문제점을 확인 - ')
print()
print()

fold_iris_frm = pd.DataFrame(data    = fold_iris.data , 
                             columns = fold_iris.feature_names)
fold_iris_frm['target'] = fold_iris.target
# fold_iris_frm

print('value counts - ')
print(fold_iris_frm['target'].value_counts())

기존 KFold 방식의 문제점을 확인 - 


value counts - 
0    50
1    50
2    50
Name: target, dtype: int64


In [95]:
bad_fold_iris = KFold(n_splits = 3)
n_iter = 0 

In [96]:
for train_idx , test_idx in bad_fold_iris.split(fold_iris_frm) :
    # print(train_idx , test_idx)
    n_iter += 1 
    label_train = fold_iris_frm['target'].iloc[train_idx]
    label_val = fold_iris_frm['target'].iloc[test_idx]
    
    
    print('교차검증 횟수 : ' , n_iter)
    print('학습 레이블 데이터 분포 : \n' , label_train.value_counts())
    print('검증 레이블 데이터 분포 : \n' , label_val.value_counts())

교차검증 횟수 :  1
학습 레이블 데이터 분포 : 
 1    50
2    50
Name: target, dtype: int64
검증 레이블 데이터 분포 : 
 0    50
Name: target, dtype: int64
교차검증 횟수 :  2
학습 레이블 데이터 분포 : 
 0    50
2    50
Name: target, dtype: int64
검증 레이블 데이터 분포 : 
 1    50
Name: target, dtype: int64
교차검증 횟수 :  3
학습 레이블 데이터 분포 : 
 0    50
1    50
Name: target, dtype: int64
검증 레이블 데이터 분포 : 
 2    50
Name: target, dtype: int64


In [101]:
print('레이블 값의 분포를 반영해주지 못하는 문제를 해결하기 위해서 - Stratified KFold 사용')
print()
print()

skf = StratifiedKFold(n_splits = 3)
n_iter = 0 

for train_idx , test_idx in skf.split(fold_iris_frm , fold_iris_frm['target']) :
    # print(train_idx , test_idx)
    n_iter += 1 
    label_train = fold_iris_frm['target'].iloc[train_idx]
    label_val = fold_iris_frm['target'].iloc[test_idx]
    
    
    print('교차검증 횟수 : ' , n_iter)
    print('학습 레이블 데이터 분포 : \n' , label_train.value_counts())
    print('검증 레이블 데이터 분포 : \n' , label_val.value_counts())

레이블 값의 분포를 반영해주지 못하는 문제를 해결하기 위해서 - Stratified KFold 사용


교차검증 횟수 :  1
학습 레이블 데이터 분포 : 
 2    34
0    33
1    33
Name: target, dtype: int64
검증 레이블 데이터 분포 : 
 0    17
1    17
2    16
Name: target, dtype: int64
교차검증 횟수 :  2
학습 레이블 데이터 분포 : 
 1    34
0    33
2    33
Name: target, dtype: int64
검증 레이블 데이터 분포 : 
 0    17
2    17
1    16
Name: target, dtype: int64
교차검증 횟수 :  3
학습 레이블 데이터 분포 : 
 0    34
1    33
2    33
Name: target, dtype: int64
검증 레이블 데이터 분포 : 
 1    17
2    17
0    16
Name: target, dtype: int64


- 아이리스 데이터를 이용해서 StratifiedKFold 교차 검증 진행해 보자 [실습]
- random_state = 100 
- StratifiedKFold 교차검증을(3, 5) 진행 후 평균 정확도를 확인
- 회귀 X , 분류 O
- 회귀에서 지원되지 않는 이유는 회귀는 연속된 숫자 값 때문이다

In [106]:
fold_iris = load_iris()

features = fold_iris.data
labels    = fold_iris.target

dt_model = DecisionTreeClassifier(random_state = 100)

skf = StratifiedKFold(n_splits = 5)
n_iter = 0 
cv_accuracy = []

for train_idx , test_idx in skf.split(features , labels) :

    X_train , X_val = features[train_idx] , features[test_idx] 
    y_train , y_val = labels[train_idx] , labels[test_idx] 
    
    # 학습과 예측
    dt_model.fit(X_train , y_train)
    fold_pred = dt_model.predict(X_val)
    
    n_iter += 1
    
    # 학습데이터에 대한 검증 정확도 측정
    acc = accuracy_score(y_val , fold_pred)
    
    print('{} 교차검증 정확도 : {} , 학습 데이터 크기 : {} , 검증데이터 크기 : {}'.format(n_iter, acc, X_train.shape[0], X_val.shape[0]))
    print()
    cv_accuracy.append(acc)

print('교차검증 평균 정확도 : ' , np.mean(cv_accuracy) )     

1 교차검증 정확도 : 0.9666666666666667 , 학습 데이터 크기 : 120 , 검증데이터 크기 : 30

2 교차검증 정확도 : 0.9666666666666667 , 학습 데이터 크기 : 120 , 검증데이터 크기 : 30

3 교차검증 정확도 : 0.9 , 학습 데이터 크기 : 120 , 검증데이터 크기 : 30

4 교차검증 정확도 : 0.9333333333333333 , 학습 데이터 크기 : 120 , 검증데이터 크기 : 30

5 교차검증 정확도 : 1.0 , 학습 데이터 크기 : 120 , 검증데이터 크기 : 30

교차검증 평균 정확도 :  0.9533333333333334


- 위 과정을 한번에 수행해주는 함수가 존재 : cross_val_score(예측모델, 피처세트, 레이블, 성능평가 지표, 폴드 수)
- 위 과정을 절차는 폴드설정 -> 반복을 통해서 학습 및 테스트의 인덱스를 추출 -> 학습과 예측

In [121]:
fold_iris = load_iris()

features = fold_iris.data
labels    = fold_iris.target

dt_model = DecisionTreeClassifier(random_state = 100)

print('성능평가지표 accuracy , 교차검증 5회 수행 - ')

scores = cross_val_score(dt_model, features, labels, scoring='accuracy', cv=5)
print('type - ' , type(scores) , 'score - ' , scores)
print()
print('평균 검증 정확도 - ' , np.round( np.mean(scores) , 2 ) )
print()
print()

print('cross_validate - ')
scores = cross_validate(dt_model, features, labels, scoring='accuracy', cv=5)
print('type - ' , type(scores) , 'score - ' , scores)
print()
print('교차 검증 시간 - ' , scores['fit_time'])
print('교차 검증별 정확도 - ' , scores['test_score'])
print('평균 검증 정확도 - ' , np.round( np.mean(scores['test_score']) , 2 ) )

성능평가지표 accuracy , 교차검증 5회 수행 - 
type -  <class 'numpy.ndarray'> score -  [0.96666667 0.96666667 0.9        0.93333333 1.        ]

평균 검증 정확도 -  0.95


cross_validate - 
type -  <class 'dict'> score -  {'fit_time': array([0.00200009, 0.00099897, 0.00100112, 0.0009985 , 0.00200653]), 'score_time': array([0.        , 0.        , 0.        , 0.        , 0.00099659]), 'test_score': array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])}

교차 검증 시간 -  [0.00200009 0.00099897 0.00100112 0.0009985  0.00200653]
교차 검증별 정확도 -  [0.96666667 0.96666667 0.9        0.93333333 1.        ]
평균 검증 정확도 -  0.95
