## R04 ; 행렬 , 배열
- 벡터와 마찬가지로 하나의 데이터 타입만 저장할 수 있다
- 같은 데이터 타입의 열벡터 여러개가 합쳐진 형태라고 이해하자

### 행렬 생성하는 방법
- 기본적으로 열중심으로 갑이 채워진다
    1. dim()
    2. matrix()
    3. rbind() , cbind()

#### 1.dim() 
- 벡터의 차원은 1차원이었다
- 행렬의 차원은 2차원이다

In [1]:
a <- 1:10
dim(a)<-c(2,5)
a

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

#### 2.matrix(x,nrow,ncol,dimnames=NULL,byrow=F)
- 행과 열에 대한 아무 명시 없으면 기본은 1열짜리 매트릭스를 생성한다
- nrow ncol 지정가능 => 하나만 지정해도 자동계산
- dimnames 옵션으로 각 행과 열에 이름 추가 가능 => list로 넣어줘야 한다
- byrow=T 로 주면 행기준으로 값을 채운다

In [4]:
mat01<-matrix(1:10)
mat01

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

In [6]:
mat02<-matrix(1:10,2,5)
mat02
mat02<-matrix(1:10,2,5,byrow = T)
mat02

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10

In [7]:
mat03<-matrix(c(1:9),nrow=3,dimnames = list(c("row1","row2","row3"),c("col1","col2","col3")))
mat03

col1 col2 col3
row1 1    4    7   
row2 2    5    8   
row3 3    6    9

In [11]:
#직접 이름을 추가해줄 수도 있다
mat04<-matrix(1:9,ncol=3)
rownames(mat04)<-c("row1","row2","row3")
colnames(mat04)<-c("col1","col2","col3")
mat04

col1 col2 col3
row1 1    4    7   
row2 2    5    8   
row3 3    6    9

####  3.rbind() , cbind()

In [12]:
mat05<-rbind(c(1,2,3),c(4,5,6))
mat05
mat06<-cbind(c(1,2,3),c(4,5,6))
mat06


[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

#### rbind() cbind()를 통해 벡터와 행렬, 행렬과 행렬도 결합할수 있다

In [30]:
cbind(1:3,4:6,matrix(1:6,3,2))
rbind(matrix(1:6,3,2),matrix(1:6,3,2))

[,1] [,2] [,3] [,4]
[1,] 1    4    1    4   
[2,] 2    5    2    5   
[3,] 3    6    3    6

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6   
[4,] 1    4   
[5,] 2    5   
[6,] 3    6

#### 단일 값으로 행렬을 다 채울 수도 있다

In [25]:
matrix(0,4,3)
matrix(NA,4,3)

[,1] [,2] [,3]
[1,] 0    0    0   
[2,] 0    0    0   
[3,] 0    0    0   
[4,] 0    0    0

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA  
[3,] NA   NA   NA  
[4,] NA   NA   NA

### 행렬의 인덱싱
- 기본적으로 vector와 동일하다
- 다만 [,] 차원이 하나 더 존재할 뿐이다
- 행 또는 열에 해당하는 인덱스가 비어있으면 전체를 의미한다

In [17]:
mat<-matrix(1:9,nrow=3,ncol=3)
mat
mat[c(1:2),2]
mat[-1,c(1,3)]
mat[,1:2]
mat[1:2,]

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[1] 4 5

[,1] [,2]
[1,] 2    8   
[2,] 3    9

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8

#### 인덱싱을 일차원의 데이터는 벡터로 출력된다
- drop option을 통해 matrix의 형태를 유지시킬수 있다

In [22]:
mat<-matrix(1:9,nrow=3,ncol=3)
mat[,2]
class(mat[,2])       #vector
class(mat[,2,drop=F])#matrix

[1] 4 5 6

[1] "integer"

[1] "matrix"

### 행렬의 연산
- 벡터와 행렬의 연산도 가능하다
- 벡터와 동일하게 원소 대 원소의 연산이다
- 벡터는 길이가 다를때 자동으로 rep해줬지만 matrix ncol nrow에 민감하다 
- t() 전치함수 transpose
- apply(matrix,1또는2,함수명) 
    - 특정 행 또는 열 기준으로 원하는 함수 사용 가능
    - 1:행 2:열
- rowSums() colSums() rowMeans() colMeans()
    - 자주 사용되는 함수들은 굳이 apply함수 없이 이미 내장되어있다
- order(vector,decrasing=F) 
    - 인자가 벡터다
    - decreaing 옵션으로 오름차순 내림차순 선택가능

In [32]:
mat01<-matrix(1:9,nrow=3,ncol=3)
vec01<-c(1,2,3)
mat01+vec01 #=> c(1,2,3) 각 열에 다 더해진다
mat01*vec01 #=> c(1,2,3) 각 열에 다 곱해진다


[,1] [,2] [,3]
[1,] 2    5     8  
[2,] 4    7    10  
[3,] 6    9    12

[,1] [,2] [,3]
[1,] 1     4    7  
[2,] 4    10   16  
[3,] 9    18   27

In [35]:
mat01<-matrix(1:9,nrow=3,ncol=3)
mat02<-matrix(1:9,nrow=3,ncol=3)
mat01+mat01
mat01-mat01
mat01*mat01
mat01/mat01

[,1] [,2] [,3]
[1,] 2     8   14  
[2,] 4    10   16  
[3,] 6    12   18

[,1] [,2] [,3]
[1,] 0    0    0   
[2,] 0    0    0   
[3,] 0    0    0

[,1] [,2] [,3]
[1,] 1    16   49  
[2,] 4    25   64  
[3,] 9    36   81

[,1] [,2] [,3]
[1,] 1    1    1   
[2,] 1    1    1   
[3,] 1    1    1

In [34]:
mat01<-matrix(1:9,nrow=3,ncol=3)
mat02<-matrix(1:9,nrow=3,ncol=3)
mat01 %*% mat02 #행렬 * 행렬의 곱셈하느법

[,1] [,2] [,3]
[1,] 30   66   102 
[2,] 36   81   126 
[3,] 42   96   150

In [37]:
#apply함수
mat01<-matrix(1:9,nrow=3,ncol=3)
apply(mat01,1,sum)
apply(mat01,1,min)
apply(mat01,2,max)

[1] 12 15 18

[1] 1 2 3

[1] 3 6 9

In [42]:
#order(vector,decrasing=F
order(iris[,1]) # index 반환해준다 => 정확히 행 index다
iris[order(iris[,1],decreasing = T),] # 첫번째 열 기준으로 내림차순 정렬

[1]  14   9  39  43  42   4   7  23  48   3  30  12  13  25  31  46   2  10
 [19]  35  38  58 107   5   8  26  27  36  41  44  50  61  94   1  18  20  22
 [37]  24  40  45  47  99  28  29  33  60  49   6  11  17  21  32  85  34  37
 [55]  54  81  82  90  91  65  67  70  89  95 122  16  19  56  80  96  97 100
 [73] 114  15  68  83  93 102 115 143  62  71 150  63  79  84  86 120 139  64
 [91]  72  74  92 128 135  69  98 127 149  57  73  88 101 104 124 134 137 147
[109]  52  75 112 116 129 133 138  55 105 111 117 148  59  76  66  78  87 109
[127] 125 141 145 146  77 113 144  53 121 140 142  51 103 110 126 130 108 131
[145] 106 118 119 123 136 132

Sepal.Length Sepal.Width Petal.Length Petal.Width Species   
132 7.9          3.8         6.4          2.0         virginica 
118 7.7          3.8         6.7          2.2         virginica 
119 7.7          2.6         6.9          2.3         virginica 
123 7.7          2.8         6.7          2.0         virginica 
136 7.7          3.0         6.1          2.3         virginica 
106 7.6          3.0         6.6          2.1         virginica 
131 7.4          2.8         6.1          1.9         virginica 
108 7.3          2.9         6.3          1.8         virginica 
110 7.2          3.6         6.1          2.5         virginica 
126 7.2          3.2         6.0          1.8         virginica 
130 7.2          3.0         5.8          1.6         virginica 
103 7.1          3.0         5.9          2.1         virginica 
51  7.0          3.2         4.7          1.4         versicolor
53  6.9          3.1         4.9          1.5         versicolor
121 6.9          3.2         5.7          2.3         virginica 
140 6.9          3.1         5.4          2.1         virginica 
142 6.9          3.1         5.1          2.3         virginica 
77  6.8          2.8         4.8          1.4         versicolor
113 6.8          3.0         5.5          2.1         virginica 
144 6.8          3.2         5.9          2.3         virginica 
66  6.7          3.1         4.4          1.4         versicolor
78  6.7          3.0         5.0          1.7         versicolor
87  6.7          3.1         4.7          1.5         versicolor
109 6.7          2.5         5.8          1.8         virginica 
125 6.7          3.3         5.7          2.1         virginica 
141 6.7          3.1         5.6          2.4         virginica 
145 6.7          3.3         5.7          2.5         virginica 
146 6.7          3.0         5.2          2.3         virginica 
59  6.6          2.9         4.6          1.3         versicolor
76  6.6          3.0         4.4          1.4         versicolor
... ...          ...         ...          ...         ...       
26  5.0          3.0         1.6          0.2         setosa    
27  5.0          3.4         1.6          0.4         setosa    
36  5.0          3.2         1.2          0.2         setosa    
41  5.0          3.5         1.3          0.3         setosa    
44  5.0          3.5         1.6          0.6         setosa    
50  5.0          3.3         1.4          0.2         setosa    
61  5.0          2.0         3.5          1.0         versicolor
94  5.0          2.3         3.3          1.0         versicolor
2   4.9          3.0         1.4          0.2         setosa    
10  4.9          3.1         1.5          0.1         setosa    
35  4.9          3.1         1.5          0.2         setosa    
38  4.9          3.6         1.4          0.1         setosa    
58  4.9          2.4         3.3          1.0         versicolor
107 4.9          2.5         4.5          1.7         virginica 
12  4.8          3.4         1.6          0.2         setosa    
13  4.8          3.0         1.4          0.1         setosa    
25  4.8          3.4         1.9          0.2         setosa    
31  4.8          3.1         1.6          0.2         setosa    
46  4.8          3.0         1.4          0.3         setosa    
3   4.7          3.2         1.3          0.2         setosa    
30  4.7          3.2         1.6          0.2         setosa    
4   4.6          3.1         1.5          0.2         setosa    
7   4.6          3.4         1.4          0.3         setosa    
23  4.6          3.6         1.0          0.2         setosa    
48  4.6          3.2         1.4          0.2         setosa    
42  4.5          2.3         1.3          0.3         setosa    
9   4.4          2.9         1.4          0.2         setosa    
39  4.4          3.0         1.3          0.2         setosa    
43  4.4          3.2         1.3          0.2         setosa    
14  4.3          3.0         1.1       

### R에서 배열은 크게 중요하지 않다

### 배열 생성하는 법 
- 1. dim(,,) 3차원 이다
- 2. array()

In [1]:
#jupyter notebook에서 표현이 안되네 ㅎ
arr01<-c(1:24)
dim(arr01)<-c(3,4,2)
print(arr01)
arr02<-array(1:24,dim=c(3,4,2))
print(arr02)

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24



### Names 함수들
- names dimnames colnames rownames
- 위의 쓰여져 있는 함수들이 굉장히 헷갈릴 수 있다
    - 그냥 열벡터는 => names
    - 기본적으로 행과 열 단위의 데이터 들은 => dimnames colnames rownames 사용가능 (matrix,array,data.frame)
    - dimnames는 값을 list의형태로 넣어준다
    - key값을 가지고있는 경우(\$로 접근 가능한 경우) names 호출시 => key값으로 돌려줌
    - 아무리 matrix or array여도 dimension이 강제로 변경된 경우는 예외다 (차원이 1인 매트릭스, 차원이 1인 배열..)
    

In [5]:
#먼저 구조를 한번 비교해보자
mat01<-matrix(1:9,3)
str(mat01) # [1:3,1:3] 
arr02<-array(1:24,dim=c(3,4,2))
str(arr02) # [1:3,1:4,1:2]

 int [1:3, 1:3] 1 2 3 4 5 6 7 8 9
 int [1:3, 1:4, 1:2] 1 2 3 4 5 6 7 8 9 10 ...


In [45]:
#각 차원 이름
vec01<-1:4
names(vec01)<-c("a","b","c","d")
#dimnames(vec01) 열벡터는 차원이 의미가 없다
str(vec01)

mat01<-matrix(1:9,3)
#rownames(mat01)<-c("a","b","c")
#colnames(mat01)<-c("A","B","C")
dimnames(mat01)<-list(row = c("a","b","c"),column = c("A","B","C"))
#row column이라고 key 값을 준다고 저걸 mat01자체를 인덱싱할때 사용은 불가능하다
#다만 나중에 row name만들 다 추출하고싶을때 rownames(mat01) 혹은 dimnames(mat01)$row
str(mat01)
dimnames(mat01)
dimnames(mat01)$row


 Named int [1:4] 1 2 3 4
 - attr(*, "names")= chr [1:4] "a" "b" "c" "d"
 int [1:3, 1:3] 1 2 3 4 5 6 7 8 9
 - attr(*, "dimnames")=List of 2
  ..$ row   : chr [1:3] "a" "b" "c"
  ..$ column: chr [1:3] "A" "B" "C"


$row
[1] "a" "b" "c"

$column
[1] "A" "B" "C"

[1] "a" "b" "c"

In [59]:
lst01<-list(a=c(1,2,3),b=c(4,5))
str(lst01)
names(lst01)
dimnames(lst01) # NULL이다

df01<-data.frame(a=c(1,2,3),b=c(4,5,6))
str(df01)
names(df01) # colnames랑 동일 key값
rownames(df01)
colnames(df01)
dimnames(df01)

List of 2
 $ a: num [1:3] 1 2 3
 $ b: num [1:2] 4 5


[1] "a" "b"

NULL

'data.frame':	3 obs. of  2 variables:
 $ a: num  1 2 3
 $ b: num  4 5 6


[1] "a" "b"

[1] "1" "2" "3"

[1] "a" "b"

[[1]]
[1] "1" "2" "3"

[[2]]
[1] "a" "b"

####  dimension이 강제로 변경된 경우
- str()를 꼭 살펴보자
- (1d) 이런식으로 표현이 되있을거다
- indexing까지 문제를 일으킨다
    - ex) 배열인데도 (1d)인 경우 arr[] 인덱싱에서 ,를 사용하면 incorrect number of dimensions 에러난다

In [54]:
#매트릭스에서 예시
mat01<-matrix(1:3)
str(mat01)
dimnames(mat01)<-list(row = c("a","b","c"),column = c("A"))
dimnames(mat01)
names(mat01) # 여기서는 NULL이다 matrix니깐

#강제로 dimension을 1차원으로 => vector비스무리 하네?
dim(mat01)<-3
str(mat01)
dimnames(mat01)<-list(row = c("a","b","c"))
dimnames(mat01)
names(mat01) # 지금은 NULL 이 아니다

 int [1:3, 1] 1 2 3


$row
[1] "a" "b" "c"

$column
[1] "A"

NULL

 int [1:3(1d)] 1 2 3


$row
[1] "a" "b" "c"

[1] "a" "b" "c"

In [58]:
#배열에서 예시
arr01<-array(1:3,dim = c(3))
str(arr01)
dimnames(arr01)<-list(c("1","2","3")) 
names(arr01)
dimnames(arr01)

#arr01[,] 에러
arr01['1']

 int [1:3(1d)] 1 2 3


[1] "1" "2" "3"

[[1]]
[1] "1" "2" "3"

1 
1