## R07 ; list
- 리스트는 벡터나 행렬과 달리 서로 다른 데이터의 유형을 수용 가능

#### list 생성
- list()

In [1]:
# scalar vector matrix array function 다된다
lst01<- list(1.23,"Apple",c(2,3,4),matrix(1:6,3),mean)
print(lst01)


[[1]]
[1] 1.23

[[2]]
[1] "Apple"

[[3]]
[1] 2 3 4

[[4]]
     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

[[5]]
function (x, ...) 
UseMethod("mean")
<bytecode: 0x7fc1580c3958>
<environment: namespace:base>



In [3]:
lst02<- list(a=1.23,b="Apple",c=c(2,3,4),d=matrix(1:6,3),e=mean)
print(lst02)

$a
[1] 1.23

$b
[1] "Apple"

$c
[1] 2 3 4

$d
     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

$e
function (x, ...) 
UseMethod("mean")
<bytecode: 0x7fc1580c3958>
<environment: namespace:base>



In [4]:
lst03 <-list()
lst03[[1]]<-c(1,2,3)
lst03[[2]]<-matrix(1:9,3)
lst03$c <- list(lst02)
print(lst03)

[[1]]
[1] 1 2 3

[[2]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$c
$c[[1]]
$c[[1]]$a
[1] 1.23

$c[[1]]$b
[1] "Apple"

$c[[1]]$c
[1] 2 3 4

$c[[1]]$d
     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

$c[[1]]$e
function (x, ...) 
UseMethod("mean")
<bytecode: 0x7fc1580c3958>
<environment: namespace:base>





#### List 결합
- c 함수 이용

In [36]:
lst01<-list(a=1:10,b=1:10)
lst02<-list(c=1:10,d=1:10)
lst03<-c(lst01,lst02)
str(lst03)

List of 4
 $ a: int [1:10] 1 2 3 4 5 6 7 8 9 10
 $ b: int [1:10] 1 2 3 4 5 6 7 8 9 10
 $ c: int [1:10] 1 2 3 4 5 6 7 8 9 10
 $ d: int [1:10] 1 2 3 4 5 6 7 8 9 10


#### List indexing ; 벡터 행렬과 다르다
- 1.  [[ ]]            ; 원소 자체의 형식 반환 
- 2.  \$               ; 원소 자체의 형식 반환
- 3.  \[ \]            ; list 반환
- 4.  ["element_name"] ; list 반환

In [13]:
# 1.[[]] 2. $
userInfo <- list(name     = c('이강희','kangheelee')  , 
                 address  = c('seoul', 'seoul') ,
                 tel      = c('010-1111-2222','010-3333-4444') , 
                 age      = c(20, 30) , 
                 marriage = c(F,T) )

userInfo[[1]]
class(userInfo[[1]])
userInfo[["name"]]
class(userInfo[["name"]])
userInfo$name
class(userInfo$name)

[1] "이강희"     "kangheelee"

[1] "character"

[1] "이강희"     "kangheelee"

[1] "character"

[1] "이강희"     "kangheelee"

[1] "character"

In [6]:
# 3. [] 4.["element name"]
userInfo <- list(name     = c('이강희','kangheelee')  , 
                 address  = c('seoul', 'seoul') ,
                 tel      = c('010-1111-2222','010-3333-4444') , 
                 age      = c(20, 30) , 
                 marriage = c(F,T) )

print(userInfo[1])
class(userInfo[1])
print(userInfo["name"])
class(userInfo["name"])


$name
[1] "이강희"     "kangheelee"



[1] "list"

$name
[1] "이강희"     "kangheelee"



[1] "list"

#### 리스트의 원소 변경
- 어떻게 indexing 으로 접근하냐에 따라 방법이 다 다르다

In [26]:
userInfo <- list(name     = c('이강희','kangheelee')  , 
                 address  = c('seoul', 'seoul') )
#밑에 3가지 방법 다 동일
userInfo[[1]][1]<-"이"
userInfo$name
userInfo[["name"]][1]<-"강"
userInfo$name
userInfo$name[1]<-"희"
userInfo$name

[1] "이"         "kangheelee"

[1] "강"         "kangheelee"

[1] "희"         "kangheelee"

In [30]:
userInfo <- list(name     = c('이강희','kangheelee')  , 
                 address  = c('seoul', 'seoul') )
#리스트 차원에서의 접근
userInfo[1] <- list(name =c("이","kangheelee"))
userInfo$name
userInfo["name"]<-list(name =c("이","kangheelee"))
userInfo$name

[1] "이"         "kangheelee"

[1] "이"         "kangheelee"

In [7]:
# 두개이상의 원소 동시변경
userInfo <- list(name     = c('이강희','kangheelee')  , 
                 address  = c('seoul', 'seoul') )
userInfo[1:2] <- list(name = c('이','kangheelee')  , 
                 address  = c('경기', 'seoul') )
print(userInfo)
userInfo[1:2] <- c(list(name = c('이','kangheelee')), 
                 list(address  = c('경기', 'seoul')))
print(userInfo)

$name
[1] "이"         "kangheelee"

$address
[1] "경기"  "seoul"

$name
[1] "이"         "kangheelee"

$address
[1] "경기"  "seoul"



#### 원소 key 이름 변경

In [35]:
userInfo <- list(name     = c('이강희','kangheelee')  , 
                 address  = c('seoul', 'seoul') )
names(userInfo)
names(userInfo)<-c("이름","주소")
names(userInfo)

[1] "name"    "address"

[1] "이름" "주소"

#### 새로운 값을 추가 제거
- $ 이용해서 쉽게 가능

In [8]:
#추가
userInfo <- list(name     = c('이강희','kangheelee')  , 
                 address  = c('seoul', 'seoul') ,
                 tel      = c('010-1111-2222','010-3333-4444') , 
                 age      = c(20, 30) , 
                 marriage = c(F,T) )
userInfo$id <- c('show3305',"show9033")
print(userInfo)

$name
[1] "이강희"     "kangheelee"

$address
[1] "seoul" "seoul"

$tel
[1] "010-1111-2222" "010-3333-4444"

$age
[1] 20 30

$marriage
[1] FALSE  TRUE

$id
[1] "show3305" "show9033"



In [9]:
#삭제
userInfo <- list(name     = c('이강희','kangheelee')  , 
                 address  = c('seoul', 'seoul') ,
                 tel      = c('010-1111-2222','010-3333-4444') , 
                 age      = c(20, 30) , 
                 marriage = c(F,T) )
userInfo$id <- NULL
print(userInfo)

$name
[1] "이강희"     "kangheelee"

$address
[1] "seoul" "seoul"

$tel
[1] "010-1111-2222" "010-3333-4444"

$age
[1] 20 30

$marriage
[1] FALSE  TRUE



#### 다양한 데이터 타입 담을때 헷갈릴수 있다

In [23]:
lst01 <- list(one=c("one","two","three"),
              two = matrix(1:9,ncol=3),
              three = array(1:12,dim=c(2,3,2)))

newList <- c(list(1,2,lst01),lst01)
str(newList)

List of 6
 $      : num 1
 $      : num 2
 $      :List of 3
  ..$ one  : chr [1:3] "one" "two" "three"
  ..$ two  : int [1:3, 1:3] 1 2 3 4 5 6 7 8 9
  ..$ three: int [1:2, 1:3, 1:2] 1 2 3 4 5 6 7 8 9 10 ...
 $ one  : chr [1:3] "one" "two" "three"
 $ two  : int [1:3, 1:3] 1 2 3 4 5 6 7 8 9
 $ three: int [1:2, 1:3, 1:2] 1 2 3 4 5 6 7 8 9 10 ...
